site_name: Jason的笔记小屋
nav:
- '主页': index.md
- 'web开发技术基础':
  - 'web_basic/index.md'
  - 'Web的基本架构': 'web_basic/basic-structure.md'
  - 'HTML': 'web_basic/html.md'
  - 'CSS': 'web_basic/css.md'
  - 'JavaScript': 'web_basic/javascript.md'
  - 'DOM': 'web_basic/dom.md'
- '软件安全':
  - 'soft_security/index.md'
  - '软件基础': 'soft_security/basic.md'
  - '字符串安全': 'soft_security/string.md'
  - '指针安全': 'soft_security/pointer.md'
  - '动态内存管理': 'soft_security/memory-management.md'
  - '整数安全': 'soft_security/integer-security.md'
  - '格式化输出': 'soft_security/string-format.md'
  - '并发': 'soft_security/concurrency.md'
  - '文件输入输出': 'soft_security/io.md'
  - '软件安全实践': 'soft_security/practice.md'
- '网络安全':
  - 'net_security/index.md'
  - '网络安全概述': 'net_security/assets.md'
  - '网络攻击的特征': 'net_security/characteristics.md'
  - '网络攻击': 'net_security/networkattack.md'
  - 'HOOK': 'net_security/hook.md'
  - '侧信道攻击': 'net_security/side-channel.md'
  - '防火墙': 'net_security/firewall.md'
  - '入侵检测': 'net_security/ids.md'
  - '虚拟专用网': 'net_security/vpn.md'
  - '应用安全——PGP为例': 'net_security/application.md'
  - '社会工程学': 'net_security/socialengineering.md'
- '408助手':
  - '408-helper/index.md'
  - '408考试大纲（2020版）': '408-helper/what-does-408-test.md'
  - '计算机组成原理':
    - '408-helper/computer-structure/index.md'
    - '运算器': '408-helper/computer-structure/operating.md'
  - '数据结构':
    - '408-helper/data-structure/index.md'
    - '线性表': '408-helper/data-structure/linear-list.md'
    - '栈': '408-helper/data-structure/stack.md'
    - '队列': '408-helper/data-structure/queue.md'
    - '数组': '408-helper/data-structure/array.md'
    - '字符串': '408-helper/data-structure/string.md'
    - '树': '408-helper/data-structure/tree.md'
    - '图': '408-helper/data-structure/graph.md'
    - '查找': '408-helper/data-structure/searching.md'
    - '排序': '408-helper/data-structure/sorting.md'
  - '计算机网络':
    - '408-helper/computer-network/index.md'
    - '网络层': '408-helper/computer-network/network-layer.md'
  - '操作系统':
    - '408-helper/operating-system/index.md'
    - '进程管理': '408-helper/operating-system/process.md'
    - '内存管理': '408-helper/operating-system/memory.md'
    - '文件管理': '408-helper/operating-system/file.md'
    - '输入输出(I/O)管理': '408-helper/operating-system/io.md'

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 切换至白天模式
  icon:
    logo: material/cloud
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - navigation.tracking
    # - navigation.instant fix tex not reloaded at page change
    - header.autohide
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
  language: 'zh'

copyright: copyright &copy; Jason Ren 2019-2021 (<a href="https://www.fantasyroom.cn" target="_blank">fantasyroom</a>) . All rights reserved
site_description: '信息安全、前端相关'
site_author: 'Jason'
use_directory_urls: false
docs_dir: 'notes_dev'
site_dir: 'notes'
extra:
  ## uncommenet before publish ##
  # analytics:
  #   provider: google
  #   property: G-Q0FWVZ6L5Y
  # disqus: 'something'
  ## uncomment before publish ##
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jasonren0403
      name: Jason's Github
    - icon: fontawesome/brands/qq
      link: http://wpa.qq.com/msgrd?v=3&uin=727847763&site=qq&menu=yes
      name: 在QQ私聊我
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/theRealRev270
      name: J.R on twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/renjason1999
      name: My facebook page
    - icon: fontawesome/brands/discord
      link: https://discord.gg/s33UBWEPxb
      name: Join to my discussion(discord)
plugins:
  # - social:
  #     cards: !ENV [SOCIAL_CARDS, false]
  # - tags:
  #     tags_file: tags.md
  - search:
      separator: '[\s\-\.]+'
  #     lang:
  #       - en
  #       - jp
  - mermaid2:
      version: 8.13.3
      arguments:
          theme: |
            ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      fallback_to_build_date: true
      enable_creation_date: true
      exclude:
          - notes_dev/index.md
extra_javascript:
  - assets/javascripts/mermaid_config.js
  - assets/javascripts/mathjax.js
  # - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - assets/javascripts/loader.js
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.0/highlight.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/tablesort@5.2.1/src/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - assets/javascripts/doc_addins.js
  - assets/javascripts/share.js
extra_css:
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.0/styles/default.min.css
  - assets/stylesheets/ex.css
markdown_extensions:
  - abbr
  - md_in_html
  - markdown.extensions.admonition
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
