# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Jason的笔记小屋
site_url: https://note.jason0743.best/
site_description: '信息安全、前端相关笔记存放处'
site_author: 'Jason'

nav:
- '主页': index.md
- 'web开发技术基础':
  - 'Web开发绪论': 'web_basic/index.md'
  - 'Web的基本架构': 'web_basic/basic-structure.md'
  - 'HTML': 'web_basic/html.md'
  - 'CSS': 'web_basic/css.md'
  - 'JavaScript': 'web_basic/javascript.md'
  - 'DOM': 'web_basic/dom.md'
- '软件安全':
  - '软件安全绪论': 'soft_security/index.md'
  - '软件基础': 'soft_security/basic.md'
  - '字符串安全': 'soft_security/string.md'
  - '指针安全': 'soft_security/pointer.md'
  - '动态内存管理': 'soft_security/memory-management.md'
  - '整数安全': 'soft_security/integer-security.md'
  - '格式化输出': 'soft_security/string-format.md'
  - '并发': 'soft_security/concurrency.md'
  - '文件输入输出': 'soft_security/io.md'
  - '软件安全实践': 'soft_security/practice.md'
- '网络安全':
  - '网络安全绪论': 'net_security/index.md'
  - '网络安全概述': 'net_security/assets.md'
  - '网络攻击的特征': 'net_security/characteristics.md'
  - '网络攻击': 'net_security/networkattack.md'
  - 'HOOK': 'net_security/hook.md'
  - 'APT': 'net_security/apt.md'
  - '内生安全与拟态防御': 'net_security/defense.md'
  - '软件定义网络': 'net_security/sdn.md'
  - '侧信道攻击': 'net_security/side-channel.md'
  - '防火墙': 'net_security/firewall.md'
  - '入侵检测': 'net_security/ids.md'
  - '虚拟专用网': 'net_security/vpn.md'
  - '应用安全——PGP为例': 'net_security/application.md'
  - '社会工程学': 'net_security/socialengineering.md'
- 'Go 语言学习':
  - 'Go语言绪论': 'golang/index.md'
  - 'Go语言基础': 'golang/basic.md'
  - 'Go流程控制': 'golang/statement.md'
  - 'Go函数': 'golang/function.md'
  - 'Go面向对象': 'golang/oop.md'
  - '协程': 'golang/goroutine.md'
  - '网络编程': 'golang/goweb.md'
- 'Java 语言学习':
  - 'Java语言概论': 'java/index.md'
  - '语言基础知识': 'java/basic.md'
  - 'Java面向对象': 'java/oop.md'
  - 'Java异常处理': 'java/exception.md'
  - 'Java图形程序设计': 'java/graphics.md'
  - '事件处理': 'java/event.md'
  - 'Swing用户界面组件': 'java/swing.md'
- '408助手':
  - '408-helper/index.md'
  - '408考试大纲（2022版）': '408-helper/what-does-408-test.md'
  - '计算机组成原理':
    - '计组绪论': '408-helper/computer-structure/index.md'
    - '数据的表示和运算': '408-helper/computer-structure/operating.md'
    - '存储器': '408-helper/computer-structure/memory.md'
    - '指令系统': '408-helper/computer-structure/instruction.md'
    - '中央处理器（CPU）': '408-helper/computer-structure/cpu.md'
    - '总线和输入输出系统': '408-helper/computer-structure/bus-and-io.md'
  - '数据结构':
    - '数据结构绪论': '408-helper/data-structure/index.md'
    - '线性表': '408-helper/data-structure/linear-list.md'
    - '栈': '408-helper/data-structure/stack.md'
    - '队列': '408-helper/data-structure/queue.md'
    - '数组': '408-helper/data-structure/array.md'
    - '字符串': '408-helper/data-structure/string.md'
    - '树': '408-helper/data-structure/tree.md'
    - '图': '408-helper/data-structure/graph.md'
    - '查找': '408-helper/data-structure/searching.md'
    - '排序': '408-helper/data-structure/sorting.md'
  - '计算机网络':
    - '计网绪论': '408-helper/computer-network/index.md'
    - '物理层': '408-helper/computer-network/physical-layer.md'
    - '数据链路层': '408-helper/computer-network/data-link-layer.md'
    - '网络层': '408-helper/computer-network/network-layer.md'
    - '传输层': '408-helper/computer-network/transportation-layer.md'
    - '应用层': '408-helper/computer-network/application-layer.md'
  - '操作系统':
    - '操作系统绪论': '408-helper/operating-system/index.md'
    - '进程管理': '408-helper/operating-system/process.md'
    - '内存管理': '408-helper/operating-system/memory.md'
    - '文件管理': '408-helper/operating-system/file.md'
    - '输入输出(I/O)管理': '408-helper/operating-system/io.md'

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 切换至白天模式
  icon:
    logo: material/cloud
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.path  # insiders
    - header.autohide
    - toc.integrate
    - toc.follow
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: 'zh'

copyright: >-
  copyright &copy; (<a href="https://www.jason0743.space" target="_blank">Jason Ren 2019-2023</a>) . All rights reserved，<a href="#__consent">在这里改变 Cookie 设置</a>

use_directory_urls: false
docs_dir: 'notes_dev'
site_dir: 'notes'
repo_url: https://github.com/jasonren0403/notes
repo_name: jasonren0403/notes
edit_uri: edit/main/notes_dev/
extra:
  comments: true
  ## uncomment before publish ##
  analytics:
    provider: google
    property: G-Q0FWVZ6L5Y
  ## uncomment before publish ##
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jasonren0403
      name: Jason's Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/theRealRev270
      name: J.R on twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/renjason1999
      name: My facebook page
    - icon: fontawesome/brands/discord
      link: https://discord.gg/s33UBWEPxb
      name: Join to my discussion(discord)
    - icon: fontawesome/brands/mastodon
      link: https://tea.codes/@jasonpro_114
  consent:
    title: Cookie 约定
    description: >-
      嗨，欢迎光临JasonRen的笔记小站！此站将使用 Cookie 优化您的体验。关于 Cookie 的具体约定，请访问我的<a href="https://www.jason0743.space/#/privacy" target="_blank">网站</a>。
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - glightbox
#  - typeset  # insiders
#  - meta  # insiders
  - social:
      cards: !ENV [CARDS, false]
      cards_font: Noto Sans SC  # implicitly suggest font for social image sharing as Robot doesn't suggest Chinese font variants
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      fallback_to_build_date: true
      enable_creation_date: true
      exclude:
        - notes_dev/index.md
extra_javascript:
  - assets/javascripts/mathjax.js
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.0/highlight.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/tablesort@5.2.1/src/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.jsdelivr.net/npm/pangu@4.0.7/dist/browser/pangu.min.js
  - assets/javascripts/doc_addins.js
  - assets/javascripts/share.js
extra_css:
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.0.0/styles/default.min.css
  - assets/stylesheets/ex.css
markdown_extensions:
  - abbr
  - md_in_html
  - tables
  - admonition
  - toc:
      # https://github.com/squidfunk/mkdocs-material/discussions/4682
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds: {}
  - footnotes
  - attr_list
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds: {}
  - pymdownx.tilde
