name: ci
env:
  CARDS: true
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Setup build cache
        uses: actions/cache@v3
        with:
          key: jason-note-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            jason-note-
      - name: Install Python dependencies
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-glightbox pillow cairosvg
      - name: Install Vue code highlighter
        run: pip install vue-lexer
      - name: Setup Deployer
        run: |
          git config --global user.email "40999116+jasonren0403@users.noreply.github.com"
          git config --global user.name "Jason Ren"
      - name: Deploy site
        run: |
          mkdocs gh-deploy --force
          mkdocs --version
