name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup build cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('.cache/**') }}
          path: .cache
      - name: Install Python dependencies
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin
      - name: Deploy site
        run: mkdocs gh-deploy --force
